packages:
  - "packages/container/libraries/*"
  - "packages/container/tools/*"
  - "packages/docs/services/*"
  - "packages/docs/tools/*"
  - "packages/foundation/libraries/*"
  - "packages/foundation/tools/*"
  - "packages/http/libraries/*"
